spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: user_service
    password: password
  security:
   user:
    name: admin
    password: admin
   default-username-password: disable

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
